version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: crud_app_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/django
    ports:
      - "8001:8001"
    container_name: crud_app
    command: python3 manage.py runserver 0.0.0.0:8001
    depends_on:
      - db

volumes:
  postgres_data:
